version: '3.9'
services:
  postgresdb:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - parking-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - parking-network
  server:
    build:
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - ./:/app
    ports:
      - 1234:1234
    env_file:
      - .env
    depends_on:
      - postgresdb
    networks:
      - parking-network

volumes:
  parking-db:
networks:
  parking-network:
